version: '3.8'
services:
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/REProject
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=456852
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - flyway
      - db
      - rabbitmq
      - redis
    networks:
      - app-network

  redis:
    image: redis
    container_name: my--redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:management
    container_name: my-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/REProject -user=postgres -password=456852 -locations=filesystem:/flyway/sql migrate
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - C:\Users\aagdas\IdeaProjects\REProject\src\main\resources\db\migration:/flyway/sql



  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_DB: REProject
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 456852
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
