SET client_encoding = 'UTF8';

-- Create table
CREATE TABLE public.companies (
                                  company_id integer NOT NULL,
                                  company_name character varying(255) NOT NULL,
                                  total_recycle_earning_USD double precision NOT NULL
);

ALTER TABLE public.companies ALTER COLUMN company_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.companies_company_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.companies ADD CONSTRAINT companies_pkey PRIMARY KEY (company_id);

ALTER TABLE public.companies ADD CONSTRAINT company_name_unique UNIQUE (company_name);