SET client_encoding = 'UTF8';

CREATE TABLE public.countries (
                                  country_id integer NOT NULL,
                                  country_name character varying(255) NOT NULL,
                                  recycle_bonus_USD double precision NOT NULL
);

ALTER TABLE public.countries ALTER COLUMN country_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.countries_country_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.countries ADD CONSTRAINT countries_pkey PRIMARY KEY (country_id);

ALTER TABLE public.countries ADD CONSTRAINT country_name_unique UNIQUE (country_name);
