SET client_encoding = 'UTF8';

CREATE TABLE public.materials (
                                  material_id integer NOT NULL,
                                  material_name character varying(255) NOT NULL,
                                  recycle_purchase_cost_USD double precision NOT NULL,
                                  purchase_cost_USD double precision NOT NULL
);

ALTER TABLE public.materials ALTER COLUMN material_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.materials_material_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.materials ADD CONSTRAINT materials_pkey PRIMARY KEY (material_id);

ALTER TABLE public.materials ADD CONSTRAINT material_name_unique UNIQUE (material_name);