SET client_encoding = 'UTF8';

CREATE TABLE public.trucks (
                               truck_id integer NOT NULL,
                               max_capacity_Kg double precision NOT NULL,
                               is_full boolean NOT NULL
);

ALTER TABLE public.trucks ALTER COLUMN truck_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trucks_truck_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.trucks ADD CONSTRAINT trucks_pkey PRIMARY KEY (truck_id);